apiVersion: v1
kind: ConfigMap
metadata:
  name: minddiary-config
  labels:
    app: minddiary

data:
  PORT: "3000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minddiary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minddiary
  template:
    metadata:
      labels:
        app: minddiary
    spec:
      containers:
      - name: minddiary
        image: mjkang4416/mind-diary:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: minddiary-config
        - secretRef:
            name: minddiary-secret

---
apiVersion: v1
kind: Service
metadata:
  name: minddiary
spec:
  type: LoadBalancer
  selector:
    app: minddiary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Secret
metadata:
  name: minddiary-secret
  labels:
    app: minddiary
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTJQMzRKQlJONUFVSFhDVUs=
  AWS_SECRET_ACCESS_KEY: aHFlcjQ2NW1vcE1LNWlUUWtjNTh3d2trMXFpeXlKakxKNnc3SHI1Vg==
  AWS_REGION: YXAtbm9ydGhlYXN0LTI=
  AWS_S3_BUCKET_NAME: bWluZGRpYXJ5aW1hZ2VidWNrZXQ=
  DB_HOST: Y2MtZGIuYzMyc2Vnd3l3bXVlLmFwLW5vcnRoZWFzdC0yLnJkcy5hbWF6b25hd3MuY29t
  DB_USER: YWRtaW4=
  DB_PW: YWRtaW4xMjM0NQ==
  DB_PORT: MzMwNg==
  DB_NAME: Y2NfZGI=
