apiVersion: v1
kind: ConfigMap
metadata:
  name: minddiary-config
  labels:
    app: minddiary
data:
  PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minddiary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minddiary
  template:
    metadata:
      labels:
        app: minddiary
    spec:
      containers:
      - name: minddiary
        image: mjkang4416/mind-diary:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: minddiary-config
        - secretRef:
            name: minddiary-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: minddiary
spec:
  type: ClusterIp
  selector:
    app: minddiary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
